### ISSUE TITLE
"Unknown error occurred" when trying to set Disconnect delay setting

### ISSUE THREAD

**Issue by gabor-nagy-stylers** [raulgbcr/lednetwf_ble#17]
Hi,

thank you for your work, this is the only working solution for my zengge controllers.

When I try to set the `disconnect delay` in HA Integrations / LEDnetWF section by the Configure popup I'm getting an "Unknown error occured" message.

Below find the related log message:
```
  File "/config/custom_components/lednetwf_ble/config_flow.py", line 224, in async_step_user
    return self.async_create_entry(title="", data={CONF_RESET: user_input[CONF_RESET], CONF_DELAY: user_input[CONF_DELAY]})
                                                               ~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'reset'
```

Looking at the code the error seems valid, the reset key is missing from user_input. I've logged the user_input dict value: `dbg: {'delay': 120}`

I've added a check for reset key before that line:
```
            if user_input.get(CONF_RESET) is None:
                user_input[CONF_RESET] = False
```
It may be a little hacky but works :) 

Shall I create a pull request?

**Comment by 8none1** [comment]
I don't think we use the `RESET` option anywhere.  

The only functionality that uses it is this function:

https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/lednetwf.py#L268

Which doesn't seem to do very much.  It might be part of the platform requirement, but I don't think it is.

If `RESET` is unnecesary then I think it would be better to remove it entirely.

That would mean removing it from:
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/__init__.py#L16
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/__init__.py#L18
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/__init__.py#L20
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/config_flow.py#L219
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/const.py#L5
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/lednetwf.py#L121
 - https://github.com/raulgbcr/lednetwf_ble/blob/d260253f177a13ca47bee993d181fb01ae51618e/custom_components/lednetwf_ble/translations/en.json#L38

(not exhausive)

Let's see what @raulgbcr thinks.

**Comment by 8none1** [comment]
I pushed a branch with these changes in, but haven't tested it at all yet.  

https://github.com/raulgbcr/lednetwf_ble/tree/8none1/disconnectdelay

**Comment by raulgbcr** [comment]
I won't be able to test until next week, but feel free to merge them if you think its good!

**Comment by 8none1** [comment]
I found one bug, still testing.

**Comment by 8none1** [comment]
I think this is good to go.  Merging but not releasing yet.  

@gabor-nagy-stylers if you're able to test from the git repo (copy the files over the top of `custom_integrations/lednetwf_ble/` and restart HA) that would be appreciated.
