### ISSUE TITLE
Feature: add support for configuration

### ISSUE THREAD

**Issue by 8none1** [raulgbcr/lednetwf_ble#18]
Somewhat inspired by: https://github.com/raulgbcr/lednetwf_ble/issues/16

I bought a new strip of addressable LEDs which have the Zengge controller.  This controller generally works with the integration already, but there are some subtle differences in the protocol. 
I also noticed that in the app it knows the state of the lights before you even connect to them (e.g. on/off, colour etc).  It also knows how many LEDs are in the strip.  I always suspected it knew how long the strip was but I couldn't work it out.

Well, now I have worked it out!  :tada:  It is possible to detect the state, length, type and byte ordering of the strips.

Now I'm interested to add this new fun stuff to the integration.

I've spent some time learning a bit more about the inner workings of Home Assistant (I kinda wish I hadn't, it's mind bending).

In this work I've re-written quite a lot of the config_flow file.  It's still very much a work-in-progress, but shows some promise of being able to simplify the code a bit (in my opinon anyway).

There is still a long way to go, but in the interests of sharing early I've stuck it in a branch.  This branch may or may not work at any point in time. :rofl: 

Branch:  https://github.com/raulgbcr/lednetwf_ble/tree/8none1/new_models

Also, as part of this investigation I think I've worked out how to add a slider for effects speed.  I'll play with that once this is finished.

**Comment by 8none1** [comment]
P.S.  This is a long way from being suitable to merge.  Like weeks at least.

**Comment by 8none1** [comment]
![image](https://github.com/raulgbcr/lednetwf_ble/assets/6552931/bd7e7544-3a41-4b43-b91d-e9e3e860cc37)

This data should be updated from the strip.  I started on this at about 8 this morning and it finally worked about 2 minutes ago.  Time for :beers:

**Comment by 8none1** [comment]
I'm just throwing spaghetti at the wall and seeing what sticks :rofl: 

I'll let you know how I get on.  

I __really__ wish there were more examples and better documentation on the integrations in HA.

**Comment by 8none1** [comment]
Writing a learning here to remind myself in the future:

ConfigEntries are immutable.  If you wan to "reconfigure" a device provided by an integration what you actually have to do is throw away the old device instance and create a new one with the new config.  The concept of "reconfiguring" doesn't seem to really exist.  There is talk of "reconfigure" in the docs, but I can't work it out.

Clue here: https://community.home-assistant.io/t/how-do-you-modify-configuration-of-integrations-its-impossible/445070/8

**Comment by 8none1** [comment]
Man, that was hard.  :rofl: 

I think this is ready for testing. :tada: 

For anyone interested in testing this branch, I suggest you do the following:
 - Delete any LEDnetWF devices you currently have configured
 - Delete the `lednetwf_ble` directory from `custom_components` on your HA server
 - Clone/copy the branch from [here](https://github.com/raulgbcr/lednetwf_ble/tree/8none1/new_models).  You need all the files from the `custom_components/lednetwf_ble` directory to be a directory called `lednetwf_ble` inside your existing `custom_components` directory
 - Restart HA
 - Hopefully your devices will be discovered automatically and you can add them all back in

Things to test:
 - Are your devices found and added correctly?
 - Can you change the basic colour, brightness, etc?
 - Do the effects all work?
 - Can you change the speed of the effects via the new slider?
 - If you have newer devices with a built in microphone, do the "Sound reactive" modes work?  (Hint: the speed slider also sets the sensitivity of the microphone)
 - If you have white LEDs in your setup, are they discovered correctly and can you set white modes (e.g. cool, warm)

NB:  If you are using effects/modes and want to get back to normal solid RGB colours, switch to effect "Static Effect 1".  Because there are so many modes on these I haven't given them all names.

I have squashed all the bugs I can find and I'm pretty happy that this is reliable now.  However, there might be some more bugs lurking.

Also, please note that I have (once again) bricked one LED controller by sending it malformed instructions.  Please don't test this on mission critical devices.  If you want to test on something cheap and cheerful I suggest [these](https://www.aliexpress.com/item/1005006190845980.html) for less than £3

**Comment by raulgbcr** [comment]
Wait, you can brick the controllers? Thats new... Any way to reset or recover them?

**Comment by raulgbcr** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 197, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 405, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 502, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/config_flow.py", line 98, in async_step_user
    return await self.async_step_validate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/config_flow.py", line 143, in async_step_validate
    error = await self.toggle_light()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/config_flow.py", line 161, in toggle_light
    self._instance = LEDNETWFInstance(self.mac, self.hass)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/lednetwf.py", line 164, in __init__
    self._model                 = self._detect_model(service_info['manufacturer_data'])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lednetwf_ble/lednetwf.py", line 219, in _detect_model
    self._color_temp_kelvin = self._min_color_temp_kelvin + color_temp * (self._max_color_temp_kelvin - self._min_color_temp_kelvin) / 100 # CoPilot did this, is it right?
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LEDNETWFInstance' object has no attribute '_min_color_temp_kelvin'. Did you mean: 'min_color_temp_kelvin'?

`self._color_temp_kelvin = self._min_color_temp_kelvin + color_temp * (self._max_color_temp_kelvin - self._min_color_temp_kelvin) / 100 # CoPilot did this, is it right?` Seems not 🤣

**Comment by 8none1** [comment]
Urgh!  This might fix it:  https://github.com/raulgbcr/lednetwf_ble/commit/14bb8a755f48e0777459d239e4d647e423d44482

Will test later and report back on the bricking :D

**Comment by raulgbcr** [comment]
@8none1 is the `Unknown    = 0x00` of ring lights config safe to use?

**Comment by raulgbcr** [comment]
Added some fixes for the ring lights [e267395](https://github.com/raulgbcr/lednetwf_ble/commit/e267395bfda3f88a8ac8d031dc7d6e28f85b4c77)

Seems to be working now, with your changes only the strips seemed to be working, added some comments about some changes made, you may need to take a look, since they may be unsafe to assume. 

Also added other comments for deprecated stuff (in 2025) that may need to be changed, will take a look at changing that once this is all stable and tested

**Comment by raulgbcr** [comment]
Seems there is quite a bit of difference between the lights firmware version. 
The led strip I got with firmware 56.00A3.2D doesn't seem to have the changing brightness bug where you have to change the brightness of the light in order for it to make the shutdown effect. Also is a lot quicker accepting commands from the remote and BT. Original ring light is using 53.001D.10.

**Comment by 8none1** [comment]
> Also is a lot quicker accepting commands from the remote and BT.

Yeah, I found that it gave more reliable connections and reconnected faster.

**Comment by 8none1** [comment]
> @8none1 is the `Unknown = 0x00` of ring lights config safe to use?

Yes.  In fact, nothing should ever be "unknown" any more.  I think this is left over from when I started playing with it.  It should be safe to remove that entry from the enum altogether (untested).

**Comment by 8none1** [comment]
> Wait, you can brick the controllers? Thats new... Any way to reset or recover them?

So this was totally my fault.  I messed up setting the effect and wrote a word where they should have been a byte and so the payload was incorrect as far as the light was concerned.  However, rather than just ignore it, it locked up.  When I power cycled the controller it never restarted and now doesn't even show up on my Bluetooth sniffer.  So as far as I can tell is totally dead.  

This was a strip light device, so only cost me a few quid. 

The problem is fixed now and the payloads are all correct.  As far as I can tell (and I have tried) it shouldn't be possible to break lights with the integration.

What's interesting to me is that this is pretty much the same failure mode as happened to some [other lights](https://www.whizzy.org/2023-12-14-bricked-xmas/).  I fouled up the effects payload and the controller died.   Makes me wonder if there is some shared code or shared MCU on these two devices.

**Comment by raulgbcr** [comment]
@8none1 I've been using this on my latest commit for some weeks now, no issues here. Are we confident merging this or there is anything that needs more work/thinking?

**Comment by 8none1** [comment]
Sorry for the delay.

I think this line is bugged:

https://github.com/raulgbcr/lednetwf_ble/blob/e267395bfda3f88a8ac8d031dc7d6e28f85b4c77/custom_components/lednetwf_ble/lednetwf.py#L277

It's still generating a 16 bit number and trying to store it in a byte.

**Comment by 8none1** [comment]
Pushed.

There might be some other general tidying up to do, but my feeling is that we're ready to merge this branch and release it.  :rocket:

**Comment by raulgbcr** [comment]
> Sorry for the delay.
> 

No worries, we just have time when we do ;)
