### ISSUE TITLE
ESPHome BT proxy support?

### ISSUE THREAD

**Issue by scottcopus** [raulgbcr/lednetwf_ble#27]
Does this work with HA ESPHome BT proxies too? If so (or not) can you update the README? Thanks.

**Comment by raulgbcr** [comment]
Take a look at #1 but TLDR, i have no idea how these work and they doesn't seem to support whats being done here, so for my part they are not supported. Feel free to tinker with them and open a PR if you know how they work and how to adapt the code here to make them work reliably
