### ISSUE TITLE
Error adding entities for domain light with platform lednetwf_ble

### ISSUE THREAD

**Issue by Lifth1309** [raulgbcr/lednetwf_ble#3]
Thanks for this Integration, i've been sitting on a useless ring led for quite some time! This integration revived it - it worked right out the gate. Unfortunately it stopped doing that at some point. Not sure when and why. At the moment i can add the device via bluetooth mac and it does blink during setup. But afterwards it says no devices and no entities under the chosen name.

I assume i messed something by deleting and readding the device. Any suggestions what to do?

Log says:

```
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:619
Integration: Licht ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 15:28:14 (2 occurrences)
Last logged: 15:28:14

    Error adding entities for domain light with platform lednetwf_ble
    Error while setting up lednetwf_ble platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: homeassistant.helpers.device_registry.DeviceRegistry.async_get_or_create() got multiple values for keyword argument 'config_entry_id'
```

**Comment by raulgbcr** [comment]
Hmmm, I have no idea what could be causing that. I would try deleting the integration completely including files and restarting HA, then try to reinstall the integration and reboot HA again to see if it happens again. Seems to me something related to HA in itself got hang up.

About the stopping to work, if it happens to you again don't remove the device it so we can take a look too.

**Comment by DIYtechie** [comment]
I have the same issue.
![IMG_2670](https://github.com/raulgbcr/lednetwf_ble/assets/20454469/d9bb487e-3a39-4f9b-81a0-a416f51f1834)
![IMG_2671](https://github.com/raulgbcr/lednetwf_ble/assets/20454469/306570e7-d540-476f-aed8-98499d17d5c8)
![IMG_2672](https://github.com/raulgbcr/lednetwf_ble/assets/20454469/33dddf18-d783-477a-b8b1-18117880560e)
![IMG_2673](https://github.com/raulgbcr/lednetwf_ble/assets/20454469/90afaffd-af0e-465d-b443-ec20cfea2e8b)
